### ISSUE TITLE
Inläsning AJAX externt quiz

### ISSUE THREAD

**Issue by cstensonpv** [Bophink/projektapp#15]
Inläsning via Firebase sker med AJAX men koden går vidare även om ingen callback finns. (Tror det är problemet iallfall) Testa att ta ett quiz direkt från home.....

**Comment by antonsivertsson** [comment]
Det fungerar, men vi vet inte säkert varför

**Comment by kevinlwhittaker** [comment]
Saknas bara att kommentera upp och se varför koden funkar :)

**Comment by kevinlwhittaker** [comment]
ingår i i ny issue
