### ISSUE TITLE
CSS chaos!

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#24]
Samordna all CSS.
Framförallt carousel.html är stökig.

**Comment by emiwes** [comment]
Jag kan börja pilla på detta, att samla allt i css dokumentet!

**Comment by emiwes** [comment]
Typ klart. Har försökt sammanställa den mesta av stylingen till css-dokumentet. All styling har numera namn som: "search-table" eller "carousel-scrollLeft", alltså "view-funktion/element". Det mesta ska också ligga i bokstavsordning. Försök att hålla er till det i fortsättningen.
