### ISSUE TITLE
Carousel fixes

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#31]
Tydliggör scrollzoner med någon typ av pil.
Testa utförligt
Fixa stoppvillkor för slideTo()

**Comment by emiwes** [comment]
Den är lite buggig när man ändrar view från search till track. Iallafall när man har få frågor inlagda, typ 3 stycken. Alla hoppar lite till höger när man kommer in i track, och förflyttar sig sen tillbaka till vänster när man kommer till search igen efter att ha lagt till en fjärde fråga.

**Comment by kevinlwhittaker** [comment]
reset scroll position vid inläsning av new quiz swenglish jäää!

**Comment by kevinlwhittaker** [comment]
kvar:
sätta overFlowRight korrekt vi initiering av karusellen.
