### ISSUE TITLE
Navbar fixes

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#33]
När är vad klickbart? gråa ut, felhantera.

Hantera login och signup knappar.

**Comment by emiwes** [comment]
Titeln på quizzet laddas inte in tillräckligt snabbt nu! Detta måste vi fixa! Antagligen något asynkront anrop som spökar...

**Comment by cstensonpv** [comment]
Jag har inget problem med det. Eller är det i ett speciellt läge?

**Comment by emiwes** [comment]
Jag gjorde en push som typ fixade detta, men jag tror att det ställer till det när man kommer in i ett quiz via länk...

**Comment by emiwes** [comment]
Titta på: https://github.com/Bophink/projektapp/commit/6d836c1198cb2442920facc6bb6d29750fce31a8

**Comment by cstensonpv** [comment]
Hittade en liten grej som jag fixat men har aldrig riktigt hittat detta problem.
