### ISSUE TITLE
Låtar hamnar i fel ordning på resultatsidan

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#36]
Låtarna på resultatsidan stämmer inte alltid överens med ordningen i quizzet.
Fel fråga kan vara kopplad till fel låt.

**Comment by emiwes** [comment]
Den verkar uppdatera hela sidan så fort man scrollar eller hoovrar över en bild för att lyssna också...
Den kör iallafall praise() och getQuestions() när man gör något av ovanstående!

**Comment by emiwes** [comment]
fixed.

**Comment by emiwes** [comment]
Jag har en fungerande kod på min datorm har inte pushat upp det än bara..
