### ISSUE TITLE
Remove, fixa emils fulkod

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#38]

**Comment by antonsivertsson** [comment]
Ska vi ta bort all kod Emil har skrivit?

**Comment by cstensonpv** [comment]
Ja! Han har väll inte tillfört något?! Haha

Nej men vi måste tänka till.med den där troll. Vi kanske kan läsa in något objekt och använda det eller jag har en idé!

**Comment by cstensonpv** [comment]
Borde räcka med en onComplete!
https://www.firebase.com/docs/web/api/firebase/set.html

**Comment by emiwes** [comment]
Calle har löst denna nu, va?

**Comment by cstensonpv** [comment]
Japp den är löst :)
