### ISSUE TITLE
Quiz interaction

### ISSUE THREAD

**Issue by kevinlwhittaker** [Bophink/projektapp#9]
~~\- poäng nedräkning + progressbar (kopplat till audiotaggen)~~
~~\- frågenummer ex 2/20~~
~~\- formatera fråga och svarsalternativ layout~~
~~\- Ändra font storlek på fråga beroende på skärmstorlek~~
- ljudeffekter?

~~\- knapparna inaktiverade efter svar~~

**Comment by emiwes** [comment]
Frågenummer ersattes med "step indicators" och nu ditsatt. Font-storlek ändras på frågan efter skärm-storlek. Frågor och svarsalternativ är lay-outade.

**Comment by emiwes** [comment]
jag stänger denna nu! Vi kanske kan finslipa mer på lay-outen. Men det vi har sagt att vi ska fixa har vi typ fixat!
